package com.sixbynine.civ3.mptools.resources

interface Strings {
  val appTitle: String

  val whatCanIBuildInModern: String
  val availableResources: String
  val descMilitia: String
  val descPartisan: String
  val descFlak: String
  val descMobileSam: String
  val descArtillery: String
  val descGalleon: String
  val descFrigate: String
  val descAttackSubmarine: String
  val descBomber: String
  val descHelicopter: String
  val descTransport: String
  val descCarrier: String
  val descRadarArtillery: String
  val descIronclad: String
  val descMarine: String
  val descConvoy: String
  val descCruiser: String
  val descInfantry: String
  val descSkirmishers: String
  val descNuclearSubmarine: String
  val descMiniCruise: String
  val descFighter: String
  val descModernParatrooper: String
  val descRpgInfantry: String
  val descPowerCruise: String
  val descAegisCruiser: String
  val descJetFighter: String
  val descTank: String
  val descBattalion: String
  val descSpecialForces: String
  val descSubCruise: String
  val descDestroyer: String
  val descChinook: String
  val descFighterBomber: String
  val descStealthFighter: String
  val descStealthBomber: String
  val descMechInfantry: String
  val descModernArmor: String
  val descCombatEngineer: String
  val descBattleship: String
  val descSubCruisePlus: String
  val descModernArmorPlus: String
  val descModernParatrooperPlus: String
  val descBattleshipPlus: String
  val labelMilitia: String
  val labelPartisan: String
  val labelFlak: String
  val labelMobileSam: String
  val labelArtillery: String
  val labelGalleon: String
  val labelFrigate: String
  val labelAttackSubmarine: String
  val labelBomber: String
  val labelHelicopter: String
  val labelTransport: String
  val labelCarrier: String
  val labelRadarArtillery: String
  val labelIronclad: String
  val labelMarine: String
  val labelConvoy: String
  val labelCruiser: String
  val labelInfantry: String
  val labelSkirmishers: String
  val labelNuclearSubmarine: String
  val labelMiniCruise: String
  val labelFighter: String
  val labelModernParatrooper: String
  val labelRpgInfantry: String
  val labelPowerCruise: String
  val labelAegisCruiser: String
  val labelJetFighter: String
  val labelTank: String
  val labelBattalion: String
  val labelSpecialForces: String
  val labelSubCruise: String
  val labelDestroyer: String
  val labelChinook: String
  val labelFighterBomber: String
  val labelStealthFighter: String
  val labelStealthBomber: String
  val labelMechInfantry: String
  val labelModernArmor: String
  val labelCombatEngineer: String
  val labelBattleship: String
  val labelSubCruisePlus: String
  val labelModernArmorPlus: String
  val labelModernParatrooperPlus: String
  val labelBattleshipPlus: String
}

val strings: Strings = BaseStrings